set(_CATKIN_CURRENT_PACKAGE "depth_calibration")
set(depth_calibration_VERSION "0.5.2")
set(depth_calibration_MAINTAINER "Alexander Reimann <reimann.alex.88@gmail.com>")
set(depth_calibration_PACKAGE_FORMAT "1")
set(depth_calibration_BUILD_DEPENDS "roscpp" "rospy" "python-numpy" "nodelet" "std_msgs" "sensor_msgs" "libpcl-all-dev" "pcl_conversions" "pcl_ros" "opencv2" "cv_bridge" "image_geometry")
set(depth_calibration_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "python-numpy" "nodelet" "std_msgs" "sensor_msgs" "libpcl-all-dev" "pcl_conversions" "pcl_ros" "opencv2" "cv_bridge" "image_geometry")
set(depth_calibration_BUILDTOOL_DEPENDS "catkin")
set(depth_calibration_BUILDTOOL_EXPORT_DEPENDS )
set(depth_calibration_EXEC_DEPENDS "roscpp" "rospy" "python-numpy" "nodelet" "std_msgs" "sensor_msgs" "libpcl-all-dev" "pcl_conversions" "pcl_ros" "opencv2" "cv_bridge" "image_geometry")
set(depth_calibration_RUN_DEPENDS "roscpp" "rospy" "python-numpy" "nodelet" "std_msgs" "sensor_msgs" "libpcl-all-dev" "pcl_conversions" "pcl_ros" "opencv2" "cv_bridge" "image_geometry")
set(depth_calibration_TEST_DEPENDS )
set(depth_calibration_DOC_DEPENDS )
set(depth_calibration_URL_WEBSITE "")
set(depth_calibration_URL_BUGTRACKER "")
set(depth_calibration_URL_REPOSITORY "")
set(depth_calibration_DEPRECATED "")